export default function () {
    return {
            'status': 'success',
            'totals': 54,
            'data': [{
            'id': 92,
            'title': 'Content-Type 对照表',
            'subtitle': 'Content-Type,Mime-Type',
            'pic': '/upload/blog/pic/9081_type.jpg',
            'createDate': 1533263664000,
            'lastDate': 1533276847970,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': 'Content-Type(Mime-Type)对照表, 有不全的会继续更新',
            'readNumber': 331,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 90,
            'title': 'Vue框架内使用GridManager',
            'subtitle': 'vue,vue gridmanager, gridmanager',
            'pic': '/upload/blog/pic/8764_vue-gridmanager.png',
            'createDate': 1528088965000,
            'lastDate': 1553912052038,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': 'GridManager对Vue很友好，发布了针对于Vue的npm包。',
            'readNumber': 229,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 89,
            'title': 'GridManager 导出',
            'subtitle': 'GridManager导出功能',
            'pic': '/upload/blog/pic/8813_%E5%AF%BC%E5%87%BA.png',
            'createDate': 1526276639000,
            'lastDate': 1552572438482,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': 'GridManager 具有表格数据导出功能，该功能为纯前端实现，对后端无依赖。',
            'readNumber': 187,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 88,
            'title': 'GridManager 用户偏好记忆',
            'subtitle': 'GridManager 用户记忆, GridManager 用户偏好记忆',
            'pic': '/upload/blog/pic/9905_%E7%94%A8%E6%88%B7%E5%81%8F%E5%A5%BD%E8%AE%B0%E5%BF%86.png',
            'createDate': 1525929957000,
            'lastDate': 1552572302805,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': 'GridManager 会将用户的部分操作进行记忆，从而达到用户行为记忆的效果。',
            'readNumber': 84,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 87,
            'title': 'GridManager 隐藏列',
            'subtitle': 'gridmanager, 隐藏列',
            'pic': '/upload/blog/pic/3927_GridManager%E9%9A%90%E8%97%8F%E5%88%97.png',
            'createDate': 1525873470000,
            'lastDate': 1552572221008,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': 'GridManager 表格管理组件， 可以便捷的对列的显示状态进行操作。',
            'readNumber': 74,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 84,
            'title': 'js捕获错误信息',
            'subtitle': 'js error,捕获错误信息',
            'pic': '/upload/blog/pic/3533_buhuo.png',
            'createDate': 1512053637000,
            'lastDate': 1512114137868,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': '这个不是很常用的功能， 但是想收集客户端的错误信息时却很有必要了解下。 ',
            'readNumber': 95,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 83,
            'title': 'div绑定键盘事件',
            'subtitle': 'div keydown, div keyup',
            'pic': '/upload/blog/pic/2279_div%E7%BB%91%E5%AE%9A%E9%94%AE%E7%9B%98%E4%BA%8B%E4%BB%B6.png',
            'createDate': 1511696284000,
            'lastDate': 1511696645370,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': '在给如div等元素绑定键盘事件(如keydown)时， 会发现绑定是失效的。',
            'readNumber': 85,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 82,
            'title': 'GridManager 调整数据格式',
            'subtitle': 'gridmanager, gridmanager数据格式,gridmanager数据',
            'pic': '/upload/blog/pic/3185_%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F%E8%B0%83%E6%95%B4.png',
            'createDate': 1510671378000,
            'lastDate': 1552572655600,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': 'GridManager在处理数据时，需要使用规定的数据格式。而在实际场景中，或多或少存在一些格式差异。在这里将对这些差异的处理方式进行说明',
            'readNumber': 190,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 81,
            'title': 'GridManager 实现搜索',
            'subtitle': 'GridManager搜索, 表格,gridmanager',
            'pic': '/upload/blog/pic/3726_%E6%90%9C%E7%B4%A2.png',
            'createDate': 1510581680000,
            'lastDate': 1552572770014,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': '搜索功能在GridManager中的实现方式很简单，可通过setQuery方法实现。',
            'readNumber': 91,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }, {
            'id': 80,
            'title': 'GridManager宽度配置不生效与出现滚动条',
            'subtitle': 'GridManager,GridManager宽度配置不生效,GridManager出现滚动条,GridManager宽度',
            'pic': '/upload/blog/pic/3245_%E9%85%8D%E7%BD%AE.png',
            'createDate': 1508678057000,
            'lastDate': 1510722590254,
            'author': '33',
            'type': 3,
            'status': 1,
            'info': '某一例配置的宽度为100px, 而生成的宽度却不是100px，并且出现了横向滚动条?',
            'readNumber': 69,
            'praiseNumber': '0',
            'commentSum': 0,
            'username': '拭目以待',
            'photo': '/upload/user/photo/8495_1.jpg'
        }]
    };
};
